Zabz dust
team614frc/Team-614-Crescendo pull request #7
Opened 2024-02-08 23:54 UTC by zabzzz

main pr from dust pid testing

2024-02-09 22:07 UTC, minhd-vu requested changes

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/Constants.java
> -    public static final double PIVOT_MAX = 10;
break out this comment into another variable

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/Constants.java
> +    public static final int sensorPort1 = 0;
what is sensorPort1? is there a sensorPort0? if not rename this variable to something more sensible

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/RobotContainer.java
> +  private double testMotorSpeeds;
remove

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/RobotContainer.java
> +    testMotorSpeeds = 0;
remove

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/RobotContainer.java
> +    // // m_coDriverController.button(OIConstants.RIGHT_STICK_PRESS).whileTrue(new
remove these comments if you're not goign to sue them

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/Intake.java
> +// // Copyright (c) FIRST and other WPILib contributors.
these are doulbe commented fix this

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/Shooter.java
> +    if (commandTimer.get() > 2.5) {
this should be a variable

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/Shooter.java
> +    if (commandTimer.get() > 4){
just do `return commandTimer.get() > 4` it should also be a variable

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/pivot/PivotDown.java
> +// // Open Source Software; you can modify and/or share it under the terms of
remove double commetns

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/pivot/PivotDown.java
> +    if (Math.abs(RobotContainer.pivotSubsystem.getPivotMotorLHeight()) > 0 ) { //18 = pivot min height i think
remove comment and place in a variable if you need it

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/pivot/PivotPIDCommand.java
> +    // RobotContainer.pivotSubsystem.set(ManipulatorConstants.MOTOR_GRAV_SPEED);
remove comment

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/pivot/PivotUp.java
> +// // Open Source Software; you can modify and/or share it under the terms of
remove double comment

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/manipulator/pivot/PivotUp.java
> +    if (Math.abs(RobotContainer.pivotSubsystem.getPivotMotorLHeight()) < 10.9) { // 2 = pivot max height I think
remove comemnt, place in variable if needed

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/vision/LimeAlign.java
> +// // Open Source Software; you can modify and/or share it under the terms of
remove double coments

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/commands/vision/LimeAlign.java
> +// // Open Source Software; you can modify and/or share it under the terms of
or remove entire file if not using

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/subsystems/DriveSubsystem.java
> +    // m_field.setRobotPose(m_odometry.getPoseMeters());
remove if not using

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/subsystems/PivotSubsystem.java
> + * -
fix these comments, ith ink the formatting may be wiered

2024-02-09 22:07 UTC, minhd-vu commented on src/main/java/frc/robot/subsystems/PivotSubsystem.java
> +    getController().setTolerance(-2);
this should be a variable

2024-02-13 21:45 UTC, Shiv-Shah commented on src/main/java/frc/robot/subsystems/PivotPIDSub.java
> +    double feedforward = pivotfeedforward.calculate(setpoint.position, setpoint.velocity);
Why no acceleration which is 0.1? https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/feedforward.html

2024-02-23 21:06 UTC, closed without merging